export type InstitutionType = 'public' | 'private' | 'sfb' | 'payments' | 'rrb' | 'foreign';

export type SavingsAccountType =
  | 'regular'
  | 'premium_high_yield'
  | 'speciale_gold'
  | 'speciale_platinum'
  | 'womens'
  | 'senior_citizens'
  | 'digisave_youth'
  | 'kids'
  | 'giga'
  | 'speciale_activ'
  | 'pragati'
  | 'institutional'
  | 'bsbda'
  | 'govt_scheme'
  | 'nri';

export type SavingsAccountVariant = {
  id: string;
  name: string;
  bankId: string;
  type: SavingsAccountType;
  minimumBalance: string;
  minBalanceAMB?: string; // Average Monthly Balance
  documentation: string[];
  ageEligibility: {
    min: number;
    max?: number;
    description?: string;
  };
  eligibility: string[];
  features: string[];
  interestRate?: string;
  specialization?: string;
  jargonTerms: string[]; // Terms that should be highlighted
  color: string;
  colorAccent: string;
};

export type FinancialInstitution = {
  id: string;
  name: string;
  type: InstitutionType;
  tagline: string;
  savingsAccountVariants: SavingsAccountType[];
  hasZeroBalance: boolean;
  disclaimer?: string;
  color: string;
  colorAccent: string;
  logoUrl?: string;
};

// Complete directory of Indian financial institutions
export const financialInstitutions: FinancialInstitution[] = [
  // PUBLIC SECTOR BANKS (SBI Group + Others)
  {
    id: 'sbi',
    name: 'State Bank of India',
    type: 'public',
    tagline: 'India\'s Largest Bank',
    savingsAccountVariants: ['regular', 'premium_high_yield', 'speciale_gold', 'speciale_platinum', 'womens', 'senior_citizens', 'digisave_youth', 'kids', 'bsbda', 'govt_scheme', 'nri'],
    hasZeroBalance: true,
    color: '#2C3E50',
    colorAccent: '#C9A96E',
    logoUrl: '/logos/sbi.png',
  },
  {
    id: 'bob',
    name: 'Bank of Baroda',
    type: 'public',
    tagline: 'India\'s International Bank',
    savingsAccountVariants: ['regular', 'womens', 'senior_citizens', 'bsbda', 'govt_scheme'],
    hasZeroBalance: true,
    color: '#1A472A',
    colorAccent: '#00E5FF',
    logoUrl: '/logos/bob_public.png',
  },
  {
    id: 'boi',
    name: 'Bank of India',
    type: 'public',
    tagline: 'Serving India Since 1906',
    savingsAccountVariants: ['regular', 'senior_citizens', 'bsbda', 'govt_scheme'],
    hasZeroBalance: true,
    color: '#1C3144',
    colorAccent: '#00F5A0',
    logoUrl: '/logos/boi_public.png',
  },
  {
    id: 'pnb',
    name: 'Punjab National Bank',
    type: 'public',
    tagline: 'Your Finance Partner',
    savingsAccountVariants: ['regular', 'womens', 'senior_citizens', 'bsbda', 'govt_scheme'],
    hasZeroBalance: true,
    color: '#2D2D2D',
    colorAccent: '#FB7185',
    logoUrl: '/logos/pnb_public.png',
  },
  {
    id: 'union-bank',
    name: 'Union Bank of India',
    type: 'public',
    tagline: 'Good People to Bank With',
    savingsAccountVariants: ['regular', 'senior_citizens', 'bsbda', 'govt_scheme'],
    hasZeroBalance: true,
    color: '#004B87',
    colorAccent: '#2DD4BF',
    logoUrl: '/logos/ubi_public.png',
  },
  {
    id: 'canara',
    name: 'Canara Bank',
    type: 'public',
    tagline: 'With You All The Way',
    savingsAccountVariants: ['regular', 'bsbda', 'govt_scheme'],
    hasZeroBalance: true,
    color: '#8B0000',
    colorAccent: '#C9A96E',
    logoUrl: '/logos/canara_public.png',
  },

  // PRIVATE SECTOR BANKS (Premium Selection)
  {
    id: 'hdfc',
    name: 'HDFC Bank',
    type: 'private',
    tagline: 'We Understand Your World',
    savingsAccountVariants: ['regular', 'premium_high_yield', 'speciale_gold', 'speciale_platinum', 'womens', 'senior_citizens', 'digisave_youth', 'kids', 'giga', 'speciale_activ', 'bsbda', 'nri'],
    hasZeroBalance: true,
    color: '#0052CC',
    colorAccent: '#38BDF8',
    logoUrl: '/logos/hdfc.png',
  },
  {
    id: 'icici',
    name: 'ICICI Bank',
    type: 'private',
    tagline: 'We Pursue Excellence',
    savingsAccountVariants: ['regular', 'premium_high_yield', 'speciale_gold', 'womens', 'senior_citizens', 'digisave_youth', 'kids', 'bsbda', 'nri'],
    hasZeroBalance: true,
    color: '#003D7A',
    colorAccent: '#FB7185',
    logoUrl: '/logos/icici.png',
  },
  {
    id: 'axis',
    name: 'Axis Bank',
    type: 'private',
    tagline: 'Progressing India',
    savingsAccountVariants: ['regular', 'premium_high_yield', 'speciale_gold', 'womens', 'senior_citizens', 'digisave_youth', 'bsbda', 'nri'],
    hasZeroBalance: true,
    color: '#1A1F71',
    colorAccent: '#00E5FF',
    logoUrl: '/logos/axis.png',
  },
  {
    id: 'kotak',
    name: 'Kotak Mahindra Bank',
    type: 'private',
    tagline: 'Let\'s Make Money Simple',
    savingsAccountVariants: ['regular', 'premium_high_yield', 'speciale_gold', 'digisave_youth', 'kids', 'bsbda'],
    hasZeroBalance: true,
    color: '#C60C30',
    colorAccent: '#00F5A0',
    logoUrl: '/logos/kmb.png',
  },
  {
    id: 'idfc',
    name: 'IDFC First Bank',
    type: 'private',
    tagline: 'Bank for a Better Tomorrow',
    savingsAccountVariants: ['regular', 'womens', 'senior_citizens', 'digisave_youth', 'bsbda'],
    hasZeroBalance: true,
    color: '#004687',
    colorAccent: '#2DD4BF',
    logoUrl: '/logos/idfc.png',
  },
  {
    id: 'fed-bank',
    name: 'Federal Bank',
    type: 'private',
    tagline: 'Your Trusted Banking Partner',
    savingsAccountVariants: ['regular', 'womens', 'senior_citizens', 'bsbda'],
    hasZeroBalance: true,
    color: '#0066CC',
    colorAccent: '#C9A96E',
    logoUrl: '/logos/federal.png',
  },
  {
    id: 'indusind',
    name: 'IndusInd Bank',
    type: 'private',
    tagline: 'Individually Customized Banking',
    savingsAccountVariants: ['regular', 'premium_high_yield', 'womens', 'senior_citizens', 'bsbda'],
    hasZeroBalance: true,
    color: '#003366',
    colorAccent: '#38BDF8',
    logoUrl: '/logos/indusind.png',
  },
  {
    id: 'yes-bank',
    name: 'Yes Bank',
    type: 'private',
    tagline: 'Experience Our Exceptionalism',
    savingsAccountVariants: ['regular', 'womens', 'senior_citizens', 'digisave_youth', 'bsbda'],
    hasZeroBalance: true,
    color: '#004D99',
    colorAccent: '#FB7185',
    logoUrl: '/logos/yesbank.png',
  },

  // SMALL FINANCE BANKS
  {
    id: 'au-sfb',
    name: 'AU Small Finance Bank',
    type: 'sfb',
    tagline: 'Bringing Finance Closer to You',
    savingsAccountVariants: ['regular', 'womens', 'senior_citizens', 'bsbda', 'pragati'],
    hasZeroBalance: true,
    color: '#E31F24',
    colorAccent: '#00E5FF',
    logoUrl: '/logos/au_sfb.png',
  },
  {
    id: 'jana-sfb',
    name: 'Jana Small Finance Bank',
    type: 'sfb',
    tagline: 'Banking for All',
    savingsAccountVariants: ['regular', 'womens', 'senior_citizens', 'bsbda', 'pragati'],
    hasZeroBalance: true,
    color: '#E91E8C',
    colorAccent: '#FFB300',
    logoUrl: '/logos/jana_sfb.png',
  },
  {
    id: 'equitas-sfb',
    name: 'Equitas Small Finance Bank',
    type: 'sfb',
    tagline: 'Inclusive Banking for All',
    savingsAccountVariants: ['regular', 'senior_citizens', 'bsbda', 'pragati'],
    hasZeroBalance: true,
    color: '#2DD4BF',
    colorAccent: '#00F5A0',
    logoUrl: '/logos/equitas_sfb.png',
  },
  {
    id: 'ujjivan-sfb',
    name: 'Ujjivan Small Finance Bank',
    type: 'sfb',
    tagline: 'Your Neighborhood Bank',
    savingsAccountVariants: ['regular', 'womens', 'bsbda', 'pragati'],
    hasZeroBalance: true,
    color: '#0066CC',
    colorAccent: '#C9A96E',
    logoUrl: '/logos/ujjivan_sfb.png',
  },
  {
    id: 'suryoday-sfb',
    name: 'Suryoday Small Finance Bank',
    type: 'sfb',
    tagline: 'Empowering Every Individual',
    savingsAccountVariants: ['regular', 'bsbda', 'pragati'],
    hasZeroBalance: true,
    color: '#FF9800',
    colorAccent: '#38BDF8',
    logoUrl: '/logos/suryoday_sfb.png',
  },
  {
    id: 'north-east-sfb',
    name: 'North East Small Finance Bank',
    type: 'sfb',
    tagline: 'Banking for Northeast India',
    savingsAccountVariants: ['regular', 'bsbda', 'pragati'],
    hasZeroBalance: true,
    color: '#004687',
    colorAccent: '#FB7185',
    logoUrl: '/logos/northeast_sfb.png',
  },

  // PAYMENTS BANKS
  {
    id: 'ippb',
    name: 'India Post Payments Bank',
    type: 'payments',
    tagline: 'Banking at Every Post Office',
    savingsAccountVariants: ['regular', 'bsbda', 'govt_scheme'],
    hasZeroBalance: true,
    color: '#D32F2F',
    colorAccent: '#00E5FF',
    disclaimer: 'Regulatory payments bank with limited services',
  },
  {
    id: 'fino-pb',
    name: 'Fino Payments Bank',
    type: 'payments',
    tagline: 'Financial Inclusion for All',
    savingsAccountVariants: ['regular', 'bsbda', 'govt_scheme'],
    hasZeroBalance: true,
    color: '#1565C0',
    colorAccent: '#00F5A0',
    disclaimer: 'Payments bank - Limited transactional features',
    logoUrl: '/logos/fino_pb.png',
  },
  {
    id: 'airtel-pb',
    name: 'Airtel Payments Bank',
    type: 'payments',
    tagline: 'Banking in Your Pocket',
    savingsAccountVariants: ['regular', 'bsbda'],
    hasZeroBalance: true,
    color: '#E81B1C',
    colorAccent: '#2DD4BF',
    disclaimer: 'Airtel Payments Bank - Mobile-first digital banking',
    logoUrl: '/logos/airtel_pb.png',
  },

  // REGIONAL RURAL BANKS
  {
    id: 'baroda-up',
    name: 'Baroda UP Bank',
    type: 'rrb',
    tagline: 'Serving Rural Communities',
    savingsAccountVariants: ['regular', 'bsbda', 'pragati'],
    hasZeroBalance: true,
    color: '#8B0000',
    colorAccent: '#C9A96E',
  },
  {
    id: 'kerala-gramin',
    name: 'Kerala Gramin Bank',
    type: 'rrb',
    tagline: 'Rural Banking Solutions',
    savingsAccountVariants: ['regular', 'bsbda', 'pragati'],
    hasZeroBalance: true,
    color: '#004D40',
    colorAccent: '#38BDF8',
  },
  {
    id: 'prathama-up',
    name: 'Prathama UP Gramin Bank',
    type: 'rrb',
    tagline: 'First Step to Financial Inclusion',
    savingsAccountVariants: ['regular', 'bsbda', 'pragati'],
    hasZeroBalance: true,
    color: '#1565C0',
    colorAccent: '#FB7185',
  },

  // FOREIGN BANKS
  {
    id: 'sc-bank',
    name: 'Standard Chartered Bank',
    type: 'foreign',
    tagline: 'Here for Good',
    savingsAccountVariants: ['regular', 'speciale_gold', 'womens'],
    hasZeroBalance: false,
    color: '#0066B2',
    colorAccent: '#00E5FF',
  },
  {
    id: 'hsbc-bank',
    name: 'HSBC Bank India',
    type: 'foreign',
    tagline: 'The World\'s Local Bank',
    savingsAccountVariants: ['regular', 'womens', 'nri'],
    hasZeroBalance: false,
    color: '#003E82',
    colorAccent: '#00F5A0',
  },
  {
    id: 'dbs-bank',
    name: 'DBS Bank India (Digibank)',
    type: 'foreign',
    tagline: 'Live More, Bank Less',
    savingsAccountVariants: ['regular', 'digisave_youth'],
    hasZeroBalance: true,
    color: '#E60012',
    colorAccent: '#2DD4BF',
  },
];

// HDFC Bank's comprehensive savings account variants
export const hdfcSavingsAccounts: SavingsAccountVariant[] = [
  {
    id: 'hdfc-regular',
    name: 'Regular Savings Account',
    bankId: 'hdfc',
    type: 'regular',
    minimumBalance: '₹2,500 (Rural) to ₹10,000 (Urban)',
    minBalanceAMB: 'Varies by branch',
    documentation: ['Aadhaar Card', 'PAN Card', 'Form 16 or Salary Slip', 'Address Proof'],
    ageEligibility: { min: 18 },
    eligibility: ['Indian Resident', 'Valid ID Proof'],
    features: ['Core digital banking', 'Standard debit card', 'Mobile banking', 'Online fund transfers', 'Bill payment utilities'],
    jargonTerms: ['DICGC Protected', 'KYC'],
    color: '#0052CC',
    colorAccent: '#38BDF8',
  },
  {
    id: 'hdfc-savingsmax',
    name: 'SavingsMax Account',
    bankId: 'hdfc',
    type: 'premium_high_yield',
    minimumBalance: '₹25,000',
    minBalanceAMB: '₹25,000 AMB',
    documentation: ['Standard KYC', 'Income Proof'],
    ageEligibility: { min: 18 },
    eligibility: ['Salaried professionals', 'Business owners', 'Minimum income ₹5 Lakh p.a.'],
    features: [
      'Automatic sweep-out to high-interest FDs',
      'Free Platinum Debit card',
      '₹10 Lakh personal accident insurance cover',
      'Priority customer service',
      'Higher interest rates on balances',
    ],
    interestRate: '4.00% - 4.50% p.a. (on AMB ≥ ₹25k)',
    jargonTerms: ['AMB', 'Sweep-Out', 'DICGC Protected'],
    color: '#0052CC',
    colorAccent: '#00E5FF',
  },
  {
    id: 'hdfc-speciale-gold',
    name: 'Specialé Gold Savings Account',
    bankId: 'hdfc',
    type: 'speciale_gold',
    minimumBalance: '₹50,000',
    minBalanceAMB: '₹50,000 AMB',
    documentation: ['Standard KYC', 'Income Proof', 'ITR or Form 16'],
    ageEligibility: { min: 18 },
    eligibility: ['High-net-worth individuals', 'Minimum monthly income ₹1 Lakh'],
    features: [
      'Healthcare and lifestyle vouchers (₹15,000 p.a.)',
      'Dedicated relationship manager',
      'Customizable custom account numbers',
      'Unlimited free domestic ATM access',
      'Priority lounge access at airport',
      'Complimentary Taj Safaris & Resorts membership',
    ],
    interestRate: '5.00% - 5.50% p.a. (on AMB ≥ ₹50k)',
    specialization: 'Premium Banking',
    jargonTerms: ['AMB', 'Relationship Manager', 'DICGC Protected'],
    color: '#0052CC',
    colorAccent: '#C9A96E',
  },
  {
    id: 'hdfc-speciale-platinum',
    name: 'Specialé Platinum Savings Account',
    bankId: 'hdfc',
    type: 'speciale_platinum',
    minimumBalance: '₹2,000,000',
    minBalanceAMB: '₹2,000,000 relationship value',
    documentation: ['Comprehensive wealth documentation', 'Source of funds certification'],
    ageEligibility: { min: 21 },
    eligibility: ['UHNI (Ultra High Networth Individuals)', 'Relationship value ≥ ₹2 Crore'],
    features: [
      'Complimentary Taj Epicure hotel membership',
      'Free luxury airport lounge access (Globally)',
      'Lifetime annual maintenance cost (AMC) waiver on linked Demat accounts',
      'Dedicated personal banker 24/7',
      'Complimentary concierge services',
      'Priority investment advisory',
      'Free travel insurance (International)',
    ],
    interestRate: '6.00% p.a. (tiered on balance)',
    specialization: 'Ultra-Premium Wealth Management',
    jargonTerms: ['Relationship Value', 'DICGC Protected', 'UHNI'],
    color: '#0052CC',
    colorAccent: '#FB7185',
  },
  {
    id: 'hdfc-womens',
    name: 'Women\'s Savings Account',
    bankId: 'hdfc',
    type: 'womens',
    minimumBalance: '₹10,000',
    minBalanceAMB: '₹10,000 AMB',
    documentation: ['Aadhaar Card', 'PAN Card', 'Address Proof'],
    ageEligibility: { min: 18, description: 'All adult women' },
    eligibility: ['Women of all ages'],
    features: [
      'Special shopping cashbacks (2-5% on retail)',
      'Integrated personal accident insurance',
      'Preferential discount rates on personal/two-wheeler loans',
      'Free investment advisory',
      'Complimentary health checkup camps (Annual)',
    ],
    interestRate: '4.50% p.a.',
    specialization: 'Women Empowerment',
    jargonTerms: ['Cashback', 'Personal Accident Insurance', 'DICGC Protected'],
    color: '#0052CC',
    colorAccent: '#FF69B4',
  },
  {
    id: 'hdfc-senior-citizens',
    name: 'Senior Citizens Savings Account',
    bankId: 'hdfc',
    type: 'senior_citizens',
    minimumBalance: '₹10,000',
    minBalanceAMB: '₹10,000 AMB',
    documentation: ['Age Proof (Birth Certificate/Age Certificate)', 'Aadhaar Card', 'Address Proof'],
    ageEligibility: { min: 60, description: 'Ages 60 and above' },
    eligibility: ['Senior citizens aged 60+', 'Indian residents'],
    features: [
      'Free doorstep banking services',
      'Customizable healthcare assistance packages',
      'Preferential high interest rates on linked FDs',
      'Health insurance add-on (Discounted premium)',
      'Free unlimited ATM usage',
      'Quarterly periodic review of financial plans',
    ],
    interestRate: '5.00% p.a. (+ 0.50% Sr. Citizen bonus on FDs)',
    jargonTerms: ['Sr. Citizen Bonus', 'DICGC Protected', 'FD'],
    color: '#0052CC',
    colorAccent: '#00F5A0',
  },
  {
    id: 'hdfc-digisave-youth',
    name: 'DigiSave Youth Account',
    bankId: 'hdfc',
    type: 'digisave_youth',
    minimumBalance: '₹5,000',
    minBalanceAMB: '₹5,000 AMB',
    documentation: ['College ID / Age Proof', 'Aadhar Card', 'Parental Guardian consent (if <18)'],
    ageEligibility: { min: 18, max: 25, description: 'Ages 18 to 25' },
    eligibility: ['Young adults and college students'],
    features: [
      'High-cashback Millennia debit card',
      'Low-barrier entry thresholds for mutual fund SIPs (Min ₹500)',
      'Free stock trading account linkage',
      'Rewards on digital transactions',
      'Educational finance webinars',
    ],
    interestRate: '4.00% p.a.',
    specialization: 'Youth Financial Inclusion',
    jargonTerms: ['SIP', 'Cashback', 'DICGC Protected', 'Debit Card'],
    color: '#0052CC',
    colorAccent: '#2DD4BF',
  },
  {
    id: 'hdfc-kids',
    name: 'Kids Advantage / Super Kids Account',
    bankId: 'hdfc',
    type: 'kids',
    minimumBalance: '₹5,000',
    minBalanceAMB: '₹5,000 AMB',
    documentation: ['Birth Certificate', 'Parent/Guardian ID Proof', 'Address Proof'],
    ageEligibility: { min: 0, max: 18, description: 'Minors up to 18 years' },
    eligibility: ['Minors with parental/guardian linking', 'Parent must be HDFC account holder'],
    features: [
      'Auto-sweep to FD if balance crosses ₹35,000',
      'Parental control spend limit toggles',
      'Financial literacy programs',
      'Gift debit card (Physical or Virtual)',
      'Savings goal tracking tools',
    ],
    interestRate: '3.50% p.a.',
    jargonTerms: ['Sweep-Out', 'FD', 'DICGC Protected', 'Parental Controls'],
    color: '#0052CC',
    colorAccent: '#38BDF8',
  },
  {
    id: 'hdfc-giga',
    name: 'Giga Savings Account',
    bankId: 'hdfc',
    type: 'giga',
    minimumBalance: 'Nil/Flexible',
    minBalanceAMB: 'No minimum balance requirement',
    documentation: ['GST Certificate / Business Registration', 'Aadhaar Card', 'Address Proof'],
    ageEligibility: { min: 21 },
    eligibility: ['Freelancers', 'Independent professionals', 'Gig economy workers'],
    features: [
      'Relaxed non-maintenance penalty fee structures',
      'Custom invoicing tools integrated',
      'Vendor payment automation',
      'Income analytics dashboard',
      'Flexible transaction limits',
    ],
    interestRate: '2.00% - 3.00% p.a. (on deposited balance)',
    specialization: 'Gig Economy Banking',
    jargonTerms: ['Flexible Balance', 'GST', 'DICGC Protected'],
    color: '#0052CC',
    colorAccent: '#FB7185',
  },
  {
    id: 'hdfc-speciale-activ',
    name: 'Specialé Activ Account',
    bankId: 'hdfc',
    type: 'speciale_activ',
    minimumBalance: 'Zero (conditionally)',
    minBalanceAMB: 'Waived if automated SI configured',
    documentation: ['Standard KYC', 'Income Proof'],
    ageEligibility: { min: 18 },
    eligibility: ['Active salary account holders', 'Automated SI/ACH mandate executors'],
    features: [
      'Balance criteria waived if automated monthly ACH/SI transaction mandates configured',
      'Auto-investment into recommended mutual funds',
      'Priority loan approvals',
      'Preferential rates on deposits',
      'Free financial planning consultation',
    ],
    interestRate: '3.50% - 4.00% p.a. (based on SI activity)',
    jargonTerms: ['ACH', 'SI Mandates', 'DICGC Protected', 'AMB'],
    color: '#0052CC',
    colorAccent: '#C9A96E',
  },
  {
    id: 'hdfc-pragati',
    name: 'Pragati Savings Account (Farmer\'s Account)',
    bankId: 'hdfc',
    type: 'pragati',
    minimumBalance: 'Minimal quarterly threshold',
    minBalanceAMB: '₹5,000 (Seasonal flexibility)',
    documentation: ['Land ownership documents', 'Aadhaar Card', 'Address Proof'],
    ageEligibility: { min: 18 },
    eligibility: ['Farmers and agricultural professionals', 'Registered farm cooperative members'],
    features: [
      'Structured for agricultural demographics',
      'Custom cash discounts on rural retail platforms',
      'Seasonal balance flexibility',
      'Agricultural loan linkage benefits',
      'Crop insurance advisory',
    ],
    interestRate: '3.00% - 3.50% p.a.',
    specialization: 'Agricultural Banking',
    jargonTerms: ['AMB', 'Seasonal Flexibility', 'DICGC Protected'],
    color: '#0052CC',
    colorAccent: '#00E5FF',
  },
  {
    id: 'hdfc-institutional',
    name: 'Institutional Savings Account',
    bankId: 'hdfc',
    type: 'institutional',
    minimumBalance: 'Account-specific layout',
    minBalanceAMB: 'As per organizational requirements',
    documentation: ['Certificate of Incorporation', 'Board Resolution', '80G/12A Certificate (if applicable)', 'TAN/PAN'],
    ageEligibility: { min: 0, description: 'N/A for organizations' },
    eligibility: ['Registered NGOs', 'Trusts', 'Educational institutions', 'Societies', 'Cooperative bodies'],
    features: [
      'Bulk transactional processing tools',
      'Multi-user access controls',
      'Customized reporting and reconciliation',
      'Grant management integration',
      'Compliance audit ready statements',
    ],
    interestRate: '2.50% - 3.00% p.a.',
    specialization: 'Non-Profit & Institutional Banking',
    jargonTerms: ['Bulk Transactions', 'Grant Management', 'DICGC Protected'],
    color: '#0052CC',
    colorAccent: '#2DD4BF',
  },
  {
    id: 'hdfc-bsbda',
    name: 'Basic Savings Bank Deposit Account (BSBDA)',
    bankId: 'hdfc',
    type: 'bsbda',
    minimumBalance: 'ZERO (Absolute)',
    minBalanceAMB: 'No balance requirement',
    documentation: ['Aadhaar Card or ID Proof', 'Address Proof (Optional)'],
    ageEligibility: { min: 18 },
    eligibility: ['All Indian residents', 'Financially excluded populations', 'Low-income groups'],
    features: [
      'Regulatory account',
      'Free Rupay debit card',
      'Max 4 free monthly cash withdrawals',
      'Direct Benefit Transfer (DBT) reception',
      'Basic online access',
    ],
    interestRate: '0% - 1.00% p.a. (on deposited amounts)',
    specialization: 'Financial Inclusion',
    jargonTerms: ['BSBDA', 'DBT', 'Rupay Card', 'DICGC Protected'],
    color: '#0052CC',
    colorAccent: '#FB7185',
  },
  {
    id: 'hdfc-nri',
    name: 'NRI Savings Account (NRE/NRO)',
    bankId: 'hdfc',
    type: 'nri',
    minimumBalance: '₹10,000 (NRE) / ₹25,000 (NRO)',
    minBalanceAMB: 'As specified for variant',
    documentation: ['Passport', 'Visa copy', 'Foreign address proof', 'PAN Card (if applicable)'],
    ageEligibility: { min: 18 },
    eligibility: ['NRI (Non-Resident Indians)', 'Foreign currency earning individuals'],
    features: [
      'NRE: Tax-free interest on foreign currency deposits',
      'NRO: Rupee holdings from India sources',
      'Repatriation facility available',
      'Multi-currency support',
      'Remittance benefits',
      'RFC (Resident Foreign Currency) option for returning residents',
    ],
    interestRate: '5.00% - 6.00% p.a. (NRE), 3.50% - 4.00% p.a. (NRO)',
    specialization: 'Offshore/NRI Banking',
    jargonTerms: ['NRE', 'NRO', 'RFC', 'Repatriation', 'DICGC Protected'],
    color: '#0052CC',
    colorAccent: '#00F5A0',
  },
];

// Updated jargon definitions
export const updatedJargonDefinitions: Record<string, { en: string; hi: string }> = {
  AMB: {
    en: 'Average Monthly Balance (AMB) is the average of daily account balances calculated monthly. Banks use AMB to determine if minimum balance requirements are met and to calculate interest rates.',
    hi: 'AMB (औसत मासिक बैलेंस) आपके खाते के दैनिक शेष का मासिक औसत है। बैंक इसे न्यूनतम बैलेंस आवश्यकताओं को पूरा करने के लिए उपयोग करते हैं।',
  },
  'Sweep-Out': {
    en: 'An automatic feature where excess balance above a set threshold is automatically transferred to a high-interest Fixed Deposit, maximizing your savings returns.',
    hi: 'यह एक स्वचालित सुविधा है जहां निर्धारित सीमा से अधिक शेष स्वचालित रूप से उच्च-ब्याज FD में स्थानांतरित होता है।',
  },
  ACH: {
    en: 'Automated Clearing House (ACH) is an electronic network for financial transactions. ACH mandates allow automatic recurring payments like salary credits or utility bills.',
    hi: 'ACH (ऑटोमेटेड क्लीयरिंग हाउस) वित्तीय लेनदेन के लिए एक इलेक्ट्रॉनिक नेटवर्क है।',
  },
  'SI Mandates': {
    en: 'SI (Systematic Investment Plan) Mandates are standing instructions to automatically invest fixed amounts at regular intervals into mutual funds or other investments.',
    hi: 'SI (व्यवस्थित निवेश योजना) स्थायी निर्देश हैं जो नियमित अंतराल पर एक निश्चित राशि स्वचालित रूप से निवेश करते हैं।',
  },
  DBT: {
    en: 'Direct Benefit Transfer (DBT) is a government program that directly deposits welfare payments and subsidies into eligible beneficiaries\' bank accounts.',
    hi: 'DBT (प्रत्यक्ष लाभ हस्तांतरण) एक सरकारी कार्यक्रम है जो कल्याण भुगतान सीधे खाते में जमा करता है।',
  },
  'Sr. Citizen Bonus': {
    en: 'Senior Citizen Bonus is an additional interest rate offered by banks on savings and fixed deposit accounts for customers aged 60 and above.',
    hi: 'Sr. Citizen Bonus 60 वर्ष से अधिक आयु के ग्राहकों के लिए बैंकों द्वारा दिया जाने वाला अतिरिक्त ब्याज दर है।',
  },
  'Relationship Value': {
    en: 'Relationship Value is the total worth of all financial products and services a customer maintains with a bank, used to determine premium account eligibility.',
    hi: 'Relationship Value एक ग्राहक द्वारा बैंक के साथ बनाए गए सभी वित्तीय उत्पादों का कुल मूल्य है।',
  },
  UHNI: {
    en: 'Ultra High Net-worth Individual (UHNI) refers to individuals with a net worth exceeding ₹50 crore, eligible for premium wealth management services.',
    hi: 'UHNI (अल्ट्रा हाई नेट-वर्थ इंडिविजुअल) ₹50 करोड़ से अधिक की शुद्ध संपत्ति वाले व्यक्ति को संदर्भित करता है।',
  },
  'Maturity Yield': {
    en: 'Maturity Yield is the total return you receive when your Fixed Deposit or investment reaches its maturity date, including principal and accrued interest.',
    hi: 'Maturity Yield वह कुल रिटर्न है जो आप FD परिपक्वता के समय प्राप्त करते हैं।',
  },
  'DICGC Protected': {
    en: 'DICGC (Deposit Insurance & Credit Guarantee Corporation) protection means deposits up to ₹5 lakh per depositor per bank are insured by the government.',
    hi: 'DICGC सुरक्षा का अर्थ है कि आपकी जमा राशि सरकार द्वारा ₹5 लाख तक बीमित है।',
  },
  KYC: {
    en: 'Know Your Customer (KYC) is a regulatory requirement where banks verify customer identity and collect personal information to comply with anti-money laundering laws.',
    hi: 'KYC (अपने ग्राहक को जानें) एक नियामक आवश्यकता है जहां बैंक ग्राहक की पहचान सत्यापित करते हैं।',
  },
  FD: {
    en: 'Fixed Deposit (FD) is an investment instrument where you deposit a sum for a fixed period at a predetermined interest rate, guaranteed returns.',
    hi: 'FD (फिक्स्ड डिपॉजिट) एक निवेश साधन है जहां आप एक निश्चित अवधि के लिए राशि जमा करते हैं।',
  },
  BSBDA: {
    en: 'Basic Savings Bank Deposit Account (BSBDA) is a zero-balance account with minimal documentation, designed for financial inclusion of underbanked populations.',
    hi: 'BSBDA एक शून्य-बैलेंस खाता है जिसे वित्तीय समावेशन के लिए डिज़ाइन किया गया है।',
  },
  'Rupay Card': {
    en: 'RuPay Card is an Indian domestic payment card developed by NPCI, offering secure transactions with lower merchant charges compared to international cards.',
    hi: 'RuPay कार्ड NPCI द्वारा विकसित एक भारतीय घरेलू भुगतान कार्ड है।',
  },
  NRE: {
    en: 'Non-Resident External (NRE) account is for NRIs to deposit foreign currency earnings with tax-free interest benefits and repatriation privileges.',
    hi: 'NRE खाता NRIs के लिए विदेशी मुद्रा आय जमा करने के लिए है जिसमें कर-मुक्त ब्याज है।',
  },
  NRO: {
    en: 'Non-Resident Ordinary (NRO) account is for NRIs to manage Indian rupee income with limited repatriation and taxable interest.',
    hi: 'NRO खाता NRIs के लिए भारतीय रुपये की आय प्रबंधित करने के लिए है।',
  },
  RFC: {
    en: 'Resident Foreign Currency (RFC) account allows returning residents to hold foreign currency balances, offered post-repatriation of NRE funds.',
    hi: 'RFC खाता लौटने वाले निवासियों को विदेशी मुद्रा शेष रखने की अनुमति देता है।',
  },
  Repatriation: {
    en: 'Repatriation is the process of transferring foreign currency or funds from overseas accounts back to India, subject to RBI regulations.',
    hi: 'Repatriation विदेशी मुद्रा को भारत वापस स्थानांतरित करने की प्रक्रिया है।',
  },
  GST: {
    en: 'Goods & Services Tax (GST) is India\'s unified indirect tax applied to the supply of goods and services, filed by business entities.',
    hi: 'GST (वस्तु एवं सेवा कर) भारत का एकीकृत अप्रत्यक्ष कर है।',
  },
  'Parental Controls': {
    en: 'Parental Controls are spending limit settings that parents can configure on their children\'s bank accounts to manage expenditure and teach financial discipline.',
    hi: 'Parental Controls माता-पिता द्वारा बच्चों के खाते पर खर्च की सीमा निर्धारित करने के लिए सेट किए जाते हैं।',
  },
  'Vendor Payment Automation': {
    en: 'Automated bill payment system where recurring vendor payments are scheduled and processed automatically based on pre-configured instructions.',
    hi: 'स्वचालित विक्रेता भुगतान प्रणाली जहां आवर्ती भुगतान स्वचालित रूप से संसाधित होते हैं।',
  },
};
